version: "3.4"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    expose:
      - "3000"
    image: app/react
    container_name: app_container
    command: npm start