version: "3.4"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "80:3000"
    expose:
      - "3000"
    image: app/react
    container_name: app_container
    command: >
      sh -c "npm i react-native-scripts --save &&
              npm start"