version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: client-app/Dockerfile
#    volumes:
#      - .:/client-app
    ports:
      - "3000:3000"
    image: app/react
    container_name: app_container
    command: npm start